//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortfolyoSiteDBEntities : DbContext
    {
        public PortfolyoSiteDBEntities()
            : base("name=PortfolyoSiteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Giris> Tbl_Giris { get; set; }
        public virtual DbSet<Tbl_Gorsel> Tbl_Gorsel { get; set; }
        public virtual DbSet<Tbl_GorselOneri> Tbl_GorselOneri { get; set; }
        public virtual DbSet<Tbl_Kategori> Tbl_Kategori { get; set; }
        public virtual DbSet<Tbl_Profil> Tbl_Profil { get; set; }
        public virtual DbSet<Tbl_Uyelik> Tbl_Uyelik { get; set; }
    }
}
